services:
  app:
    # TODO - Build an image to use, targeting the dev stage
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev

    # TODO - Expose port 3000 from the container to port 3000 on the host
    ports:
      - 3000:3000

    # TODO - Mount the src directory to /usr/local/app/src
    volumes:
      - type: bind
        source: ./src
        target: /usr/local/app/src
  
  mongo:
    # TODO - Specify the mongo image. Not really any additional config to provide
    image: mongo

  mongo-express:
    # TODO - Use the mongo-express image
    image: mongo-express

    # TODO - Export the container's port 8081 to the host at port 8081
    ports:
      - 8081:8081
